(() => {
    'use strict';

    kintone.events.on('app.record.create.show' ,(event) =>{
        console.log(event);
        event.record.Table.value = [
          {
            'value':{
              'Action5':{
                'type':'DROP_DOWN',
                'value':'あくなき探求'
              },
              '課題':{
                'type':'MULTI_LINE_TEXT',
                'value':'',
              },
              '状況':{
                'type':'CHECK_BOX',
                'value':['未振り返り']
              }
            }
          },
          {
            'value':{
              'Action5':{
                'type':'DROP_DOWN',
                'value':'不屈の心体'
              },
              '課題':{
                'type':'MULTI_LINE_TEXT',
                'value':'',
              },
              '状況':{
                'type':'CHECK_BOX',
                'value':['未振り返り']
              }
            }
          },
          {
            'value':{
              'Action5':{
                'type':'DROP_DOWN',
                'value':'理想への共感'
              },
              '課題':{
                'type':'MULTI_LINE_TEXT',
                'value':'',
              },
              '状況':{
                'type':'CHECK_BOX',
                'value':['未振り返り']
              }
            }
          },
          {
            'value':{
              'Action5':{
                'type':'DROP_DOWN',
                'value':'心を動かす'
              },
              '課題':{
                'type':'MULTI_LINE_TEXT',
                'value':'',
              },
              '状況':{
                'type':'CHECK_BOX',
                'value':['未振り返り']
              }
            }
          },
          {
            'value':{
              'Action5':{
                'type':'DROP_DOWN',
                'value':'知識を増やす'
              },
              '課題':{
                'type':'MULTI_LINE_TEXT',
                'value':'',
              },
              '状況':{
                'type':'CHECK_BOX',
                'value':['未振り返り']
              }
            }
          },
          {
            'value':{
              'Action5':{
                'type':'DROP_DOWN',
                'value':'公明正大'
              },
              '課題':{
                'type':'MULTI_LINE_TEXT',
                'value':'',
              },
              '状況':{
                'type':'CHECK_BOX',
                'value':['未振り返り']
              }
            }
          }
        ];
        return event;
    });
 

})();